os: osx
language: cpp

compiler:
  - clang

cache:
  directories:
    - $HOME/Library/Caches/Homebrew
  
before_install:
  - brew update
  - brew bundle

script:
  - meson builddir --buildtype release
  - ninja -C builddir
  
before_cache:
  - brew cleanup